"""
PostgreSQL Neon — Capa de Persistencia Relacional del SMA
==========================================================
Gestiona todas las operaciones con la BD PostgreSQL en Neon:

  schema público:
    - public.Solicitudes_Documentos     (documentos ciudadanos y correspondencia)
    - public.Clasificacion_Agente       (resultado clasificación distribuidor)
    - public.Clasificacion_Comision     (resultado clasificación comisión)
    - public.articulos_constitucion     (lectura RAG constitucional)

  schema sistema:
    - sistema.proyecto_ley              (registro maestro de proyectos legislativos)
    - sistema.bitacora_proceso          (auditoría de cada etapa del pipeline)
    - sistema.enrutamiento_documento    (tracking de mensajes inter-agente)
    - sistema.comision                  (catálogo de comisiones — solo lectura)
    - sistema.observaciones_constitucionales  ← NUEVA TABLA
"""

import os
from datetime import datetime
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

load_dotenv()

try:
    from loguru import logger
except ImportError:
    import logging
    logger = logging.getLogger("sma_neon")


# ── Lazy singleton de conexión ────────────────────────────────────────────────
_conn = None
_tables_ensured = False


def get_conn():
    """Retorna una conexión psycopg2 a Neon PostgreSQL (singleton)."""
    global _conn, _tables_ensured
    try:
        if _conn is not None and not _conn.closed:
            # Test that connection is alive
            with _conn.cursor() as cur:
                cur.execute("SELECT 1")
            return _conn
    except Exception:
        _conn = None

    try:
        import psycopg2

        url = os.getenv("NEON_DATABASE_URL", "")
        if not url:
            raise ValueError("NEON_DATABASE_URL no configurada en .env")

        _conn = psycopg2.connect(url, connect_timeout=10)
        _conn.autocommit = True
        logger.info("✅ PostgreSQL Neon conectado")
        
        if not _tables_ensured:
            _tables_ensured = True
            try:
                _ensure_observaciones_table(_conn)
                _ensure_consistencia_tables(_conn)
                _ensure_articulos_normativos_table(_conn)
                _ensure_usuarios_table(_conn)
            except Exception as em:
                logger.warning(f"Aviso durante ensure_tables Neon: {em}")
        return _conn
    except Exception as e:
        logger.error(f"❌ No se pudo conectar a PostgreSQL Neon: {e}")
        raise


def ping_neon() -> bool:
    """Retorna True si Neon PostgreSQL responde correctamente."""
    try:
        conn = get_conn()
        with conn.cursor() as cur:
            cur.execute("SELECT 1")
        return True
    except Exception:
        return False



# ── Creación y migración automática de tablas ─────────────────────────────────

def _ensure_proyecto_ley_columns(conn) -> None:
    """Verifica y asegura las columnas exactas requeridas para sistema.proyecto_ley."""
    ddl = """
    CREATE TABLE IF NOT EXISTS sistema.proyecto_ley (
        id_proyecto                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        numero_expediente           VARCHAR(50),
        id_usuario_presentante      INTEGER DEFAULT 1,
        titulo                      TEXT,
        resumen                     TEXT,
        texto_completo              TEXT,
        archivo_pdf                 VARCHAR(255),
        fecha_ingreso               TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        id_estado_actual            INTEGER DEFAULT 1,
        id_comision_actual          INTEGER,
        prioridad                   VARCHAR(20) DEFAULT 'Media',
        numero_ley_asignado         VARCHAR(50),
        fecha_publicacion           DATE,
        fecha_vigencia              DATE,
        activo                      BOOLEAN DEFAULT TRUE,
        observaciones_generales     TEXT,
        drive_file_id               VARCHAR(255),
        drive_link                  TEXT
    );
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS numero_expediente VARCHAR(50);
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS id_usuario_presentante INTEGER DEFAULT 1;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS titulo TEXT;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS resumen TEXT;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS texto_completo TEXT;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS archivo_pdf VARCHAR(255);
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS fecha_ingreso TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS id_estado_actual INTEGER DEFAULT 1;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS id_comision_actual INTEGER;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS prioridad VARCHAR(20) DEFAULT 'Media';
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS numero_ley_asignado VARCHAR(50);
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS fecha_publicacion DATE;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS fecha_vigencia DATE;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS observaciones_generales TEXT;
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS drive_file_id VARCHAR(255);
    ALTER TABLE sistema.proyecto_ley ADD COLUMN IF NOT EXISTS drive_link TEXT;
    """
    try:
        cur = conn.cursor()
        cur.execute(ddl)
        conn.commit()
        cur.close()
        logger.info("✅ Tabla sistema.proyecto_ley verificada y columnas aseguradas")
    except Exception as e:
        conn.rollback()
        logger.warning(f"No se pudo asegurar columnas de proyecto_ley: {e}")


def _ensure_usuarios_table(conn) -> None:
    """Crea/migra public."Usuarios_Sistema" (login por rol).

    Nota: la columna `contrasena` se guarda en texto plano a propósito —
    es un esquema de prueba/demo, sin hashing. No usar tal cual en producción.
    """
    ddl = """
    CREATE TABLE IF NOT EXISTS public."Usuarios_Sistema" (
        usuario_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_completo     VARCHAR(200) NOT NULL,
        correo_electronico  VARCHAR(200) NOT NULL UNIQUE,
        rol                 VARCHAR(50)  NOT NULL DEFAULT 'Ciudadano',
        telefono            VARCHAR(30),
        fecha_creacion      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        activo              BOOLEAN DEFAULT TRUE,
        contrasena          VARCHAR(200)
    );
    ALTER TABLE public."Usuarios_Sistema" ADD COLUMN IF NOT EXISTS telefono VARCHAR(30);
    ALTER TABLE public."Usuarios_Sistema" ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE;
    ALTER TABLE public."Usuarios_Sistema" ADD COLUMN IF NOT EXISTS contrasena VARCHAR(200);
    """
    with conn.cursor() as cur:
        cur.execute(ddl)
    logger.info('✅ Tabla public."Usuarios_Sistema" verificada/migrada (roles: Senador, Diputado, Operador_Mesa_Partes, Ciudadano, etc.)')


def autenticar_usuario(correo_electronico: str, contrasena: str) -> Optional[Dict[str, Any]]:
    """Valida credenciales contra public."Usuarios_Sistema".

    Contraseña comparada en texto plano (entorno de prueba, sin hashing).
    Retorna el usuario (sin la contraseña) si las credenciales son correctas
    y la cuenta está activa; None en caso contrario.
    """
    try:
        import psycopg2.extras
        conn = get_conn()
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute(
            """
            SELECT usuario_id, nombre_completo, correo_electronico, rol,
                   telefono, fecha_creacion, activo
            FROM public."Usuarios_Sistema"
            WHERE correo_electronico = %s AND contrasena = %s
            """,
            (correo_electronico, contrasena),
        )
        row = cur.fetchone()
        cur.close()
        if not row or not row.get("activo", True):
            return None
        return dict(row)
    except Exception as e:
        logger.warning(f"Error autenticando usuario: {e}")
        return None


def crear_usuario_ciudadano(
    nombre_completo: str,
    correo_electronico: str,
    contrasena: str,
    telefono: Optional[str] = None,
) -> Dict[str, Any]:
    """Auto-registro público: crea un nuevo usuario con rol fijo 'Ciudadano'."""
    import psycopg2.extras
    conn = get_conn()
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        cur.execute(
            'SELECT usuario_id FROM public."Usuarios_Sistema" WHERE correo_electronico = %s',
            (correo_electronico,),
        )
        if cur.fetchone():
            raise ValueError("Ya existe un usuario registrado con ese correo electrónico")

        cur.execute(
            """
            INSERT INTO public."Usuarios_Sistema"
                (nombre_completo, correo_electronico, rol, telefono, contrasena, activo)
            VALUES (%s, %s, 'Ciudadano', %s, %s, TRUE)
            RETURNING usuario_id, nombre_completo, correo_electronico, rol,
                      telefono, fecha_creacion, activo
            """,
            (nombre_completo, correo_electronico, telefono, contrasena),
        )
        row = cur.fetchone()
        return dict(row)
    finally:
        cur.close()


def obtener_usuarios_por_rol(rol: str) -> List[Dict[str, Any]]:
    """Devuelve los usuarios activos de public."Usuarios_Sistema" que tienen el rol indicado
    (p. ej. 'Senador' o 'Diputado'). Se usa para armar la lista de destinatarios cuando
    una cámara confirma la aprobación de un proyecto y hay que notificar a la cámara opuesta.
    """
    try:
        import psycopg2.extras
        conn = get_conn()
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute(
            """
            SELECT usuario_id, nombre_completo, correo_electronico, rol, telefono
            FROM public."Usuarios_Sistema"
            WHERE rol = %s AND (activo IS NULL OR activo = TRUE)
            ORDER BY nombre_completo
            """,
            (rol,),
        )
        rows = cur.fetchall()
        cur.close()
        return [dict(r) for r in rows]
    except Exception as e:
        logger.warning(f"No se pudieron obtener usuarios con rol '{rol}': {e}")
        return []


def _ensure_observaciones_table(conn) -> None:
    """Crea la tabla sistema.observaciones_constitucionales si no existe."""
    _ensure_proyecto_ley_columns(conn)
    ddl = """
    CREATE TABLE IF NOT EXISTS sistema.observaciones_constitucionales (
        id_observacion          SERIAL PRIMARY KEY,
        id_proyecto             INTEGER
                                    REFERENCES sistema.proyecto_ley(id_proyecto)
                                    ON DELETE SET NULL,
        sesion_id               VARCHAR(36)  NOT NULL,
        task_id_mongo           VARCHAR(36),

        -- Resultado del agente verificador constitucional
        valido                  BOOLEAN      NOT NULL DEFAULT TRUE,
        confianza               NUMERIC(5,2),
        severidad_maxima        VARCHAR(20)
                                    CHECK (severidad_maxima IN
                                        ('ninguna','leve','grave','bloqueante')),
        num_contradicciones     INTEGER      DEFAULT 0,
        fundamentacion          TEXT,

        -- Detalle en JSONB
        contradicciones         JSONB        DEFAULT '[]'::jsonb,
        analisis_articulos      JSONB        DEFAULT '[]'::jsonb,
        articulos_consultados   JSONB        DEFAULT '[]'::jsonb,

        -- Metadatos de ejecución
        modelo_llm              VARCHAR(100),
        duracion_ms             INTEGER,
        fecha_analisis          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

        -- Estado del dictamen
        estado_dictamen         VARCHAR(30)  DEFAULT 'emitido'
                                    CHECK (estado_dictamen IN
                                        ('emitido','revisado','apelado','firme'))
    );
    CREATE INDEX IF NOT EXISTS idx_obs_const_proyecto
        ON sistema.observaciones_constitucionales(id_proyecto);
    CREATE INDEX IF NOT EXISTS idx_obs_const_sesion
        ON sistema.observaciones_constitucionales(sesion_id);
    CREATE INDEX IF NOT EXISTS idx_obs_const_valido
        ON sistema.observaciones_constitucionales(valido);
    CREATE INDEX IF NOT EXISTS idx_obs_const_severidad
        ON sistema.observaciones_constitucionales(severidad_maxima);
    CREATE INDEX IF NOT EXISTS idx_obs_const_fecha
        ON sistema.observaciones_constitucionales(fecha_analisis DESC);
    """
    try:
        cur = conn.cursor()
        cur.execute(ddl)
        conn.commit()
        cur.close()
        logger.info("✅ Tabla sistema.observaciones_constitucionales verificada/creada")
    except Exception as e:
        conn.rollback()
        logger.warning(f"No se pudo crear tabla observaciones_constitucionales: {e}")


# ════════════════════════════════════════════════════════════════════════════
# OBSERVACIONES CONSTITUCIONALES (tabla nueva)
# ════════════════════════════════════════════════════════════════════════════

def guardar_observacion_constitucional(
    sesion_id: str,
    dictamen: Dict[str, Any],
    id_proyecto: Optional[int] = None,
    task_id_mongo: Optional[str] = None,
    modelo_llm: str = "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
    duracion_ms: int = 0,
    articulos_consultados: Optional[List] = None,
) -> Optional[int]:
    """Guarda el dictamen del agente verificador constitucional."""
    try:
        from psycopg2.extras import Json
        conn = get_conn()
        cur = conn.cursor()

        valido = bool(dictamen.get("valido", True))
        confianza = float(dictamen.get("confianza", 0)) if dictamen.get("confianza") is not None else None
        severidad = str(dictamen.get("severidad_maxima", "ninguna")).lower()
        if severidad not in ("ninguna", "leve", "grave", "bloqueante"):
            severidad = "ninguna"

        contradicciones = dictamen.get("contradicciones", [])
        analisis = dictamen.get("analisis_articulos", [])
        # Usar el parámetro explícito si viene, si no tomar del dictamen
        consultados = articulos_consultados if articulos_consultados is not None else dictamen.get("articulos_consultados", [])
        fundamentacion = dictamen.get("fundamentacion_general", "")
        num_contradicciones = len(contradicciones) if isinstance(contradicciones, list) else 0

        cur.execute(
            """
            INSERT INTO sistema.observaciones_constitucionales (
                id_proyecto, sesion_id, task_id_mongo,
                valido, confianza, severidad_maxima, num_contradicciones,
                fundamentacion, contradicciones, analisis_articulos,
                articulos_consultados, modelo_llm, duracion_ms,
                fecha_analisis, estado_dictamen
            ) VALUES (
                %s, %s, %s,
                %s, %s, %s, %s,
                %s, %s, %s,
                %s, %s, %s,
                NOW(), 'emitido'
            )
            RETURNING id_observacion
            """,
            (
                id_proyecto,
                sesion_id,
                task_id_mongo,
                valido,
                confianza,
                severidad,
                num_contradicciones,
                fundamentacion,
                Json(contradicciones),
                Json(analisis),
                Json(consultados),
                modelo_llm,
                duracion_ms,
            ),
        )
        row = cur.fetchone()
        conn.commit()
        cur.close()
        id_obs = row[0] if row else None
        logger.info(f"✅ Observación constitucional guardada → id: {id_obs} (válido={valido}, severidad={severidad})")
        return id_obs
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo guardar observacion_constitucional en Neon: {e}")
        return None


def obtener_observacion_por_proyecto(id_proyecto: int) -> Optional[Dict[str, Any]]:
    """Obtiene la última observación constitucional de un proyecto."""
    try:
        import psycopg2.extras
        conn = get_conn()
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute(
            """
            SELECT * FROM sistema.observaciones_constitucionales
            WHERE id_proyecto = %s
            ORDER BY fecha_analisis DESC
            LIMIT 1
            """,
            (id_proyecto,),
        )
        row = cur.fetchone()
        cur.close()
        return dict(row) if row else None
    except Exception as e:
        logger.warning(f"No se pudo consultar observación: {e}")
        return None


def obtener_observacion_por_sesion(sesion_id: str) -> Optional[Dict[str, Any]]:
    """Obtiene la observación constitucional por sesion_id."""
    try:
        import psycopg2.extras
        conn = get_conn()
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute(
            """
            SELECT * FROM sistema.observaciones_constitucionales
            WHERE sesion_id = %s
            ORDER BY fecha_analisis DESC
            LIMIT 1
            """,
            (sesion_id,),
        )
        row = cur.fetchone()
        cur.close()
        return dict(row) if row else None
    except Exception as e:
        logger.warning(f"No se pudo consultar observación por sesión: {e}")
        return None


def obtener_stats_constitucionales() -> Dict[str, Any]:
    """KPIs agregados de auditoría constitucional."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute("""
            SELECT
                COUNT(*) as total,
                COUNT(*) FILTER (WHERE valido = TRUE) as conformes,
                COUNT(*) FILTER (WHERE valido = FALSE) as con_contradicciones,
                COUNT(*) FILTER (WHERE severidad_maxima = 'bloqueante') as bloqueantes,
                COUNT(*) FILTER (WHERE severidad_maxima = 'grave') as graves,
                AVG(confianza) as promedio_confianza,
                SUM(num_contradicciones) as total_contradicciones
            FROM sistema.observaciones_constitucionales
        """)
        row = cur.fetchone()
        cur.close()
        if row:
            return {
                "total": row[0] or 0,
                "conformes": row[1] or 0,
                "con_contradicciones": row[2] or 0,
                "bloqueantes": row[3] or 0,
                "graves": row[4] or 0,
                "promedio_confianza": round(float(row[5] or 0), 1),
                "total_contradicciones": row[6] or 0,
            }
        return {"total": 0, "conformes": 0, "con_contradicciones": 0, "bloqueantes": 0, "graves": 0, "promedio_confianza": 0.0, "total_contradicciones": 0}
    except Exception as e:
        logger.warning(f"No se pudieron obtener stats constitucionales: {e}")
        return {"total": 0, "conformes": 0, "con_contradicciones": 0, "bloqueantes": 0, "graves": 0, "promedio_confianza": 0.0, "total_contradicciones": 0}


def obtener_ultimas_observaciones(limit: int = 10) -> List[Dict[str, Any]]:
    """Últimas N observaciones con datos del proyecto."""
    try:
        import psycopg2.extras
        conn = get_conn()
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute(
            """
            SELECT
                o.id_observacion,
                o.id_proyecto,
                o.sesion_id,
                o.valido,
                o.confianza,
                o.severidad_maxima,
                o.num_contradicciones,
                o.fundamentacion,
                o.fecha_analisis,
                o.estado_dictamen,
                p.titulo as titulo_proyecto,
                p.numero_expediente
            FROM sistema.observaciones_constitucionales o
            LEFT JOIN sistema.proyecto_ley p ON o.id_proyecto = p.id_proyecto
            ORDER BY o.fecha_analisis DESC
            LIMIT %s
            """,
            (limit,),
        )
        rows = [dict(r) for r in cur.fetchall()]
        cur.close()
        for r in rows:
            if isinstance(r.get("fecha_analisis"), datetime):
                r["fecha_analisis"] = r["fecha_analisis"].strftime("%Y-%m-%d %H:%M:%S")
        return rows
    except Exception as e:
        logger.warning(f"No se pudieron obtener observaciones: {e}")
        return []


# ════════════════════════════════════════════════════════════════════════════
# PROYECTO LEY & ASIGNACIÓN DE COMISIÓN
# ════════════════════════════════════════════════════════════════════════════

def guardar_proyecto_ley(
    sesion_id: str,
    texto_documento: str,
    nombre_archivo: Optional[str] = None,
    comision_data: Optional[Dict[str, Any]] = None,
    dictamen: Optional[Dict[str, Any]] = None,
    tipo_entrada: str = "Texto",
    drive_file_id: Optional[str] = None,
    drive_link: Optional[str] = None,
) -> Optional[int]:
    """
    Inserta o actualiza un proyecto de ley en sistema.proyecto_ley con el esquema exacto:
    (id_proyecto, numero_expediente, id_usuario_presentante, titulo, resumen, texto_completo,
     archivo_pdf, fecha_ingreso, id_estado_actual, id_comision_actual, prioridad,
     numero_ley_asignado, fecha_publicacion, fecha_vigencia, activo, observaciones_generales)
    """
    try:
        conn = get_conn()
        cur = conn.cursor()

        comision_data = comision_data or {}
        dictamen = dictamen or {}

        prioridad_map = {
            "urgente": "Urgente", "alta": "Alta",
            "normal": "Media", "media": "Media",
            "baja": "Baja",
        }
        prioridad = prioridad_map.get(
            str(comision_data.get("prioridad", "Media")).lower(), "Media"
        )

        titulo = str(comision_data.get("resumen", nombre_archivo or "Proyecto de Ley")).split("\n")[0][:400]
        resumen = str(comision_data.get("resumen", ""))[:2000]
        comision_sugerida = str(comision_data.get("comision_principal", ""))
        
        # Buscar id_comision si ya se tiene la sugerida
        id_comision = None
        if comision_sugerida:
            cur.execute(
                """
                SELECT id_comision FROM sistema.comision 
                WHERE LOWER(nombre_comision) = LOWER(%s)
                   OR LOWER(nombre_corto) = LOWER(%s)
                   OR LOWER(codigo_comision) = LOWER(%s)
                   OR %s ILIKE CONCAT('%%', nombre_corto, '%%')
                LIMIT 1
                """,
                (comision_sugerida, comision_sugerida, comision_sugerida, comision_sugerida)
            )
            c_row = cur.fetchone()
            if c_row:
                id_comision = c_row[0]

        # Generar número de expediente correlativo si es nuevo
        ano_actual = datetime.now().year
        num_exp = f"PL-{ano_actual}-{sesion_id[:6].upper()}"

        # Buscar si ya existe un proyecto con este sesion_id
        cur.execute(
            "SELECT id_proyecto FROM sistema.proyecto_ley WHERE observaciones_generales LIKE %s LIMIT 1",
            (f"%sesion:{sesion_id}%",),
        )
        existing = cur.fetchone()

        if existing:
            id_proyecto = existing[0]
            cur.execute(
                """
                UPDATE sistema.proyecto_ley SET
                    titulo = %s,
                    resumen = %s,
                    id_comision_actual = COALESCE(%s, id_comision_actual),
                    prioridad = %s,
                    drive_file_id = COALESCE(%s, drive_file_id),
                    drive_link = COALESCE(%s, drive_link)
                WHERE id_proyecto = %s
                """,
                (titulo, resumen, id_comision, prioridad, drive_file_id, drive_link, id_proyecto),
            )
        else:
            cur.execute(
                """
                INSERT INTO sistema.proyecto_ley (
                    numero_expediente, id_usuario_presentante, titulo, resumen,
                    texto_completo, archivo_pdf, fecha_ingreso, id_estado_actual,
                    id_comision_actual, prioridad, activo, observaciones_generales,
                    drive_file_id, drive_link
                ) VALUES (
                    %s, 1, %s, %s,
                    %s, %s, NOW(), 1,
                    %s, %s, TRUE, %s,
                    %s, %s
                )
                RETURNING id_proyecto
                """,
                (
                    num_exp,
                    titulo,
                    resumen,
                    texto_documento,
                    nombre_archivo or "",
                    id_comision,
                    prioridad,
                    f"sesion:{sesion_id}",
                    drive_file_id,
                    drive_link,
                ),
            )
            row = cur.fetchone()
            id_proyecto = row[0] if row else None

        conn.commit()
        cur.close()
        logger.info(f"✅ proyecto_ley guardado en Neon → id: {id_proyecto} (Exp: {num_exp})")
        return id_proyecto
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo guardar proyecto_ley en Neon: {e}")
        return None


def asignar_comision_a_proyecto(
    id_proyecto: int,
    nombre_comision: str,
    observaciones: Optional[str] = None,
    valido_constitucional: Optional[bool] = None,
) -> Optional[int]:
    """
    Asigna id_comision_actual y id_estado_actual a un proyecto_ley
    buscando el id_comision en sistema.comision.
    """
    try:
        conn = get_conn()
        cur = conn.cursor()

        cur.execute(
            """
            SELECT id_comision, nombre_comision FROM sistema.comision 
            WHERE LOWER(nombre_comision) = LOWER(%s)
               OR LOWER(nombre_corto) = LOWER(%s)
               OR LOWER(codigo_comision) = LOWER(%s)
               OR %s ILIKE CONCAT('%%', nombre_corto, '%%')
               OR %s ILIKE CONCAT('%%', nombre_comision, '%%')
            LIMIT 1
            """,
            (nombre_comision, nombre_comision, nombre_comision, nombre_comision, nombre_comision)
        )
        row = cur.fetchone()
        id_comision = row[0] if row else None
        nombre_oficial = row[1] if row else nombre_comision

        # id_estado_actual: 2 = Derivado a Comisión, 3 = Con Observación Constitucional
        id_estado = 3 if valido_constitucional is False else 2

        obs_texto = f"\n[Comisión Asignada]: {nombre_oficial}"
        if observaciones:
            obs_texto += f"\n[Detalle]: {observaciones}"

        cur.execute(
            """
            UPDATE sistema.proyecto_ley SET
                id_comision_actual = %s,
                id_estado_actual = %s,
                observaciones_generales = CONCAT(COALESCE(observaciones_generales, ''), %s)
            WHERE id_proyecto = %s
            """,
            (id_comision, id_estado, obs_texto, id_proyecto)
        )
        conn.commit()
        cur.close()
        logger.info(f"✅ Comisión '{nombre_oficial}' (id_comision={id_comision}) asignada al proyecto #{id_proyecto}")
        return id_comision
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"No se pudo asignar comisión al proyecto #{id_proyecto}: {e}")
        return None


def actualizar_proyecto_con_observacion(id_proyecto: int, id_observacion: int, valido: bool) -> None:
    """Actualiza el estado de trámite del proyecto_ley según el dictamen constitucional."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        nuevo_estado = 3 if not valido else 2  # 3=Observado, 2=En Comision
        cur.execute(
            "UPDATE sistema.proyecto_ley SET id_estado_actual = %s WHERE id_proyecto = %s",
            (nuevo_estado, id_proyecto),
        )
        conn.commit()
        cur.close()
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo actualizar estado del proyecto: {e}")



# ════════════════════════════════════════════════════════════════════════════
# SOLICITUDES (ciudadanas y correspondencia)
# ════════════════════════════════════════════════════════════════════════════

# ════════════════════════════════════════════════════════════════════════════
# SOLICITUDES Y EXPEDIENTES UNIFICADOS (Esquema sistema.proyecto_ley)
# ════════════════════════════════════════════════════════════════════════════

def guardar_solicitud_documento(
    sesion_id: str,
    texto_documento: str,
    tipo_entrada: str,
    nombre_archivo: Optional[str] = None,
    origen: str = "Sistema",
    resumen_ia: Optional[str] = None,
    drive_file_id: Optional[str] = None,
    drive_link: Optional[str] = None,
    usuario_id: int = 1,
) -> Optional[int]:
    """
    Guarda en sistema.proyecto_ley unificando peticiones ciudadanas,
    oficios y correspondencia (reemplaza public.Solicitudes_Documentos).
    """
    try:
        conn = get_conn()
        cur = conn.cursor()
        
        tipo_doc = "Peticion_Ciudadana" if "ciudadan" in origen.lower() else ("Oficio" if "oficio" in origen.lower() or "corresp" in origen.lower() else "Peticion_Ciudadana")
        titulo = (nombre_archivo or "Documento Mesa de Partes")[:400]
        resumen = (resumen_ia or texto_documento[:500])[:2000]
        ano_actual = datetime.now().year
        num_exp = f"DOC-{ano_actual}-{sesion_id[:6].upper()}"

        cur.execute(
            """
            INSERT INTO sistema.proyecto_ley (
                numero_expediente, id_usuario_presentante, titulo, resumen,
                texto_completo, archivo_pdf, fecha_ingreso, id_estado_actual,
                prioridad, activo, tipo_documento, observaciones_generales,
                drive_file_id, drive_link
            ) VALUES (
                %s, %s, %s, %s,
                %s, %s, NOW(), 1,
                'Media', TRUE, %s, %s,
                %s, %s
            )
            RETURNING id_proyecto
            """,
            (
                num_exp,
                usuario_id,
                titulo,
                resumen,
                texto_documento[:50000],
                (nombre_archivo or "")[:255],
                tipo_doc,
                f"origen:{origen} | sesion:{sesion_id}",
                drive_file_id,
                drive_link,
            ),
        )
        row = cur.fetchone()
        conn.commit()
        cur.close()
        proyecto_id = row[0] if row else None
        logger.info(f"✅ Documento guardado en sistema.proyecto_ley → id: {proyecto_id} (Tipo: {tipo_doc})")
        return proyecto_id
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo guardar documento en sistema.proyecto_ley: {e}")
        return None


def guardar_clasificacion_agente(
    solicitud_id: Optional[int],
    agente_destino: str,
    confianza_modelo: Optional[float] = None,
) -> None:
    """Registra la clasificación en la bitácora y en sistema.proyecto_ley."""
    if solicitud_id is None:
        return
    try:
        from psycopg2.extras import Json
        conn = get_conn()
        cur = conn.cursor()
        decision = {
            "agente_destino": agente_destino,
            "confianza": confianza_modelo,
            "timestamp": datetime.now().isoformat()
        }
        cur.execute(
            """
            UPDATE sistema.proyecto_ley 
            SET agente_distribuidor_decision = %s
            WHERE id_proyecto = %s
            """,
            (Json(decision), solicitud_id)
        )
        conn.commit()
        cur.close()
        logger.debug(f"Clasificación actualizada en proyecto_ley #{solicitud_id}")
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo actualizar clasificación en proyecto_ley: {e}")


def guardar_clasificacion_comision(
    solicitud_id: Optional[int],
    comision_data: Dict[str, Any],
    dictamen: Optional[Dict[str, Any]] = None,
    cosmos_document_id: Optional[str] = None,
    drive_file_id: Optional[str] = None,
    drive_link: Optional[str] = None,
) -> None:
    """Actualiza la comisión sugerida directamente en sistema.proyecto_ley."""
    if solicitud_id is None:
        return
    try:
        nombre_comision = str(comision_data.get("comision_principal", ""))
        asignar_comision_a_proyecto(
            id_proyecto=solicitud_id,
            nombre_comision=nombre_comision,
            observaciones=comision_data.get("resumen", ""),
        )
    except Exception as e:
        logger.warning(f"⚠️  No se pudo guardar comision en proyecto_ley: {e}")


# ════════════════════════════════════════════════════════════════════════════
# PASOS DE PROCESO (Historial visual y retroceso)
# ════════════════════════════════════════════════════════════════════════════

def registrar_paso_proceso(
    sesion_id: str,
    num_paso: int,
    nombre_paso: str,
    agente_responsable: str,
    justificacion_paso: str,
    estado_paso: str = "EN_PROGRESO",
    id_proyecto: Optional[int] = None,
    resultado: Optional[Dict[str, Any]] = None,
    duracion_segundos: int = 0,
) -> Optional[int]:
    """Registra o actualiza el paso de un agente en sistema.pasos_proceso."""
    try:
        from psycopg2.extras import Json
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO sistema.pasos_proceso (
                id_proyecto, sesion_id, num_paso, nombre_paso,
                justificacion_paso, agente_responsable, estado_paso,
                resultado, timestamp_inicio, timestamp_fin, duracion_segundos
            ) VALUES (
                %s, %s, %s, %s,
                %s, %s, %s,
                %s, NOW(), CASE WHEN %s = 'COMPLETADO' THEN NOW() ELSE NULL END, %s
            )
            RETURNING id
            """,
            (
                id_proyecto,
                sesion_id,
                num_paso,
                nombre_paso,
                justificacion_paso,
                agente_responsable,
                estado_paso,
                Json(resultado or {}),
                estado_paso,
                duracion_segundos,
            )
        )
        row = cur.fetchone()
        conn.commit()
        cur.close()
        return row[0] if row else None
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️ No se pudo registrar paso de proceso: {e}")
        return None


def obtener_pasos_proceso(sesion_id: str) -> List[Dict[str, Any]]:
    """Recupera los pasos ejecutados para una sesión específica."""
    try:
        import psycopg2.extras
        conn = get_conn()
        cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
        cur.execute(
            """
            SELECT * FROM sistema.pasos_proceso
            WHERE sesion_id = %s
            ORDER BY num_paso ASC, timestamp_inicio ASC
            """,
            (sesion_id,)
        )
        rows = [dict(r) for r in cur.fetchall()]
        cur.close()
        for r in rows:
            if isinstance(r.get("timestamp_inicio"), datetime):
                r["timestamp_inicio"] = r["timestamp_inicio"].isoformat()
            if isinstance(r.get("timestamp_fin"), datetime):
                r["timestamp_fin"] = r["timestamp_fin"].isoformat()
        return rows
    except Exception as e:
        logger.warning(f"No se pudieron obtener pasos de proceso: {e}")
        return []



# ════════════════════════════════════════════════════════════════════════════
# BITÁCORA Y ENRUTAMIENTO
# ════════════════════════════════════════════════════════════════════════════

def registrar_bitacora(
    id_proyecto: Optional[int],
    agente_accion: str,
    accion_realizada: str,
    descripcion: str = "",
    tipo_agente: str = "IA",
    tiempo_segundos: Optional[int] = None,
    nivel_confianza: Optional[float] = None,
    metadata: Optional[Dict] = None,
    es_publico: bool = True,
) -> None:
    """Registra un paso del pipeline en sistema.bitacora_proceso."""
    try:
        from psycopg2.extras import Json
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO sistema.bitacora_proceso (
                id_proyecto, agente_accion, tipo_agente, fecha_hora,
                accion_realizada, descripcion_detallada,
                metadata, es_publico,
                tiempo_duracion_segundos, nivel_confianza
            ) VALUES (
                %s, %s, %s, NOW(),
                %s, %s,
                %s, %s,
                %s, %s
            )
            """,
            (
                id_proyecto,
                agente_accion[:100],
                tipo_agente[:50],
                accion_realizada[:200],
                descripcion[:2000],
                Json(metadata or {}),
                es_publico,
                tiempo_segundos,
                nivel_confianza,
            ),
        )
        conn.commit()
        cur.close()
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo registrar bitacora: {e}")


def registrar_enrutamiento(
    id_proyecto: Optional[int],
    agente_origen: str,
    agente_destino: str,
    estado_envio: str = "completado",
    mensaje_adjunto: str = "",
    tiempo_respuesta_ms: Optional[int] = None,
    payload: Optional[Dict] = None,
    decision: str = "",
    categoria: str = "",
) -> None:
    """Registra el enrutamiento entre agentes en sistema.enrutamiento_documento."""
    try:
        from psycopg2.extras import Json
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO sistema.enrutamiento_documento (
                id_proyecto, agente_origen, agente_destino,
                fecha_envio, fecha_recepcion, estado_envio,
                mensaje_adjunto, tiempo_respuesta_ms,
                payload_json, decision_derivacion, categoria_clasificacion
            ) VALUES (
                %s, %s, %s,
                NOW(), NOW(), %s,
                %s, %s,
                %s, %s, %s
            )
            """,
            (
                id_proyecto,
                agente_origen[:100],
                agente_destino[:100],
                estado_envio[:50],
                mensaje_adjunto[:1000],
                tiempo_respuesta_ms,
                Json(payload or {}),
                decision[:500],
                categoria[:100],
            ),
        )
        conn.commit()
        cur.close()
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo registrar enrutamiento: {e}")


# ════════════════════════════════════════════════════════════════════════════
# CONSULTAS — CATÁLOGOS
# ════════════════════════════════════════════════════════════════════════════

def obtener_comisiones_activas() -> List[str]:
    """
    Lee las comisiones activas desde sistema.comision.
    Con fallback a lista hardcodeada si Neon no responde.
    """
    _FALLBACK = [
        "COMISION_DE_CONSTITUCION",
        "COMISION_DE_POLITICA_ECONOMICA",
        "COMISION_DE_OBRAS_PUBLICAS",
        "COMISION_DE_EDUCACION_CULTURA",
        "COMISION_DE_SALUD",
        "COMISION_DE_JUSTICIA_PENAL",
        "COMISION_DE_MEDIO_AMBIENTE",
        "COMISION_DE_DEFENSA_NACIONAL",
        "COMISION_DE_DERECHOS_HUMANOS",
        "COMISION_DE_ECONOMIA_PLURAL",
    ]
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """
            SELECT COALESCE(codigo_comision, nombre_corto, nombre)
            FROM sistema.comision
            WHERE activa = TRUE OR estado = 'activa'
            ORDER BY nombre
            """
        )
        rows = cur.fetchall()
        cur.close()
        if rows:
            comisiones = [r[0] for r in rows if r[0]]
            logger.info(f"📋 Comisiones cargadas desde Neon: {len(comisiones)}")
            return comisiones
        return _FALLBACK
    except Exception as e:
        logger.warning(f"Usando comisiones hardcodeadas (Neon falló): {e}")
        return _FALLBACK


def _ensure_articulos_normativos_table(conn) -> None:
    """
    Crea (si no existe) public.articulos_normativos: tabla PROPIA para todo
    cuerpo normativo que se vaya subiendo desde la pantalla "Base Legal"
    (Código Penal, Código de Minería, leyes, decretos, resoluciones...).

    OJO: esto es independiente de public.articulos_constitucion (que sigue
    siendo solo la Constitución Política del Estado, sin tocar su esquema).
    """
    dim = int(os.getenv("NVIDIA_EMBED_DIM", "2048"))
    ddl = f"""
    CREATE EXTENSION IF NOT EXISTS vector;

    CREATE TABLE IF NOT EXISTS public.articulos_normativos (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        documento           TEXT NOT NULL,
        tipo_documento      TEXT NOT NULL DEFAULT 'ley',
        numero_norma        TEXT,
        articulo_numero     TEXT NOT NULL,
        articulo_titulo     TEXT,
        contenido           TEXT NOT NULL,
        capitulo            TEXT,
        seccion             TEXT,
        estado              TEXT NOT NULL DEFAULT 'vigente',
        contenido_hash      TEXT,
        fecha_derogacion    DATE,
        norma_derogatoria   TEXT,
        embedding           vector({dim}),
        creado_en           TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        actualizado_en      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_articulos_normativos_documento
        ON public.articulos_normativos (documento);
    """
    try:
        cur = conn.cursor()
        cur.execute(ddl)
        conn.commit()
        cur.close()
        logger.info("✅ Tabla public.articulos_normativos verificada")
    except Exception as e:
        conn.rollback()
        logger.warning(f"No se pudo crear/verificar articulos_normativos: {e}")
        return

    # Restricción única e índice vectorial en pasos separados (no rompen la app si fallan)
    try:
        cur = conn.cursor()
        cur.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'articulos_normativos_doc_num_uq'
                ) THEN
                    ALTER TABLE public.articulos_normativos
                        ADD CONSTRAINT articulos_normativos_doc_num_uq UNIQUE (documento, articulo_numero);
                END IF;
            END $$;
        """)
        conn.commit()
        cur.close()
    except Exception as e:
        conn.rollback()
        logger.warning(f"No se pudo crear la restricción única (documento, articulo_numero) en articulos_normativos: {e}")

    try:
        cur = conn.cursor()
        cur.execute(f"""
            CREATE INDEX IF NOT EXISTS idx_articulos_normativos_embedding
                ON public.articulos_normativos
                USING hnsw ((embedding::halfvec({dim})) halfvec_cosine_ops);
        """)
        conn.commit()
        cur.close()
    except Exception as e:
        conn.rollback()
        logger.warning(f"No se pudo crear el índice HNSW sobre embedding (¿halfvec no disponible?): {e}")


def obtener_articulos_constitucion(texto_query: str, limit: int = 15) -> List[Dict[str, Any]]:
    """
    Busca artículos constitucionales en public.articulos_constitucion.
    Intenta las columnas 'contenido' y 'texto_articulo' con fallback.
    """
    try:
        conn = get_conn()
        cur = conn.cursor()
        palabras = [p for p in texto_query.split()[:10] if len(p) > 3]
        if not palabras:
            cur.close()
            return []

        for col in ("contenido", "texto_articulo"):
            try:
                like_clause = " OR ".join([f"{col} ILIKE %s" for _ in palabras])
                params = [f"%{p}%" for p in palabras]
                cur.execute(
                    f"""
                    SELECT
                        COALESCE(articulo_numero, '') AS numero,
                        COALESCE(articulo_titulo, '') AS titulo,
                        COALESCE({col}, '')            AS texto,
                        COALESCE(capitulo, '')         AS capitulo,
                        COALESCE(seccion, '')          AS seccion
                    FROM public.articulos_constitucion
                    WHERE {like_clause}
                    LIMIT %s
                    """,
                    params + [limit],
                )
                rows = cur.fetchall()
                cur.close()
                return [
                    {"numero": r[0], "titulo": r[1], "texto": r[2], "capitulo": r[3], "seccion": r[4]}
                    for r in rows
                ]
            except Exception:
                try:
                    conn.rollback()
                except Exception:
                    pass
                continue
        cur.close()
        return []
    except Exception as e:
        logger.warning(f"No se pudieron obtener artículos constitucionales: {e}")
        return []


def obtener_articulos_normativos(texto_query: str, limit: int = 15, documento: Optional[str] = None) -> List[Dict[str, Any]]:
    """
    Busca por palabras clave en public.articulos_normativos (Código Penal,
    Código de Minería, leyes, decretos... todo lo ingestado desde "Base Legal").
    Si `documento` se especifica, filtra solo dentro de ese cuerpo normativo.
    """
    try:
        conn = get_conn()
        cur = conn.cursor()
        palabras = [p for p in texto_query.split()[:10] if len(p) > 3]
        if not palabras:
            cur.close()
            return []

        like_clause = " OR ".join(["contenido ILIKE %s" for _ in palabras])
        params: List[Any] = [f"%{p}%" for p in palabras]
        doc_clause = ""
        if documento:
            doc_clause = " AND documento ILIKE %s"
            params.append(f"%{documento}%")
        cur.execute(
            f"""
            SELECT
                COALESCE(articulo_numero, '') AS numero,
                COALESCE(articulo_titulo, '') AS titulo,
                COALESCE(contenido, '')        AS texto,
                COALESCE(capitulo, '')         AS capitulo,
                COALESCE(seccion, '')          AS seccion,
                documento,
                tipo_documento
            FROM public.articulos_normativos
            WHERE ({like_clause}){doc_clause}
            LIMIT %s
            """,
            params + [limit],
        )
        rows = cur.fetchall()
        cur.close()
        return [
            {"numero": r[0], "titulo": r[1], "texto": r[2], "capitulo": r[3], "seccion": r[4],
             "documento": r[5], "tipo_documento": r[6]}
            for r in rows
        ]
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"No se pudieron obtener artículos normativos: {e}")
        return []


def buscar_articulos_normativos_semantico(
    embedding: List[float], documento: Optional[str] = None, top_k: int = 8, umbral: float = 0.0
) -> List[Dict[str, Any]]:
    """
    Búsqueda semántica (pgvector, similitud coseno) sobre public.articulos_normativos.
    Cubre todo lo ingestado desde "Base Legal" (Código Penal, Código de Minería, leyes...).
    """
    try:
        conn = get_conn()
        cur = conn.cursor()
        literal = _embedding_a_literal_pgvector(embedding)
        params: List[Any] = [literal]
        doc_clause = ""
        if documento:
            doc_clause = "AND documento ILIKE %s"
            params.append(f"%{documento}%")
        params.extend([literal, top_k])
        cur.execute(
            f"""
            SELECT
                COALESCE(articulo_numero, '') AS numero,
                COALESCE(articulo_titulo, '') AS titulo,
                COALESCE(contenido, '')        AS texto,
                documento,
                tipo_documento,
                1 - (embedding <=> %s::vector) AS similitud
            FROM public.articulos_normativos
            WHERE embedding IS NOT NULL {doc_clause}
            ORDER BY embedding <=> %s::vector
            LIMIT %s
            """,
            params,
        )
        filas = cur.fetchall()
        cur.close()
        resultado = [
            {"numero": f[0], "titulo": f[1], "texto": f[2], "documento": f[3],
             "tipo_documento": f[4], "similitud": float(f[5])}
            for f in filas
        ]
        return [r for r in resultado if r["similitud"] >= umbral]
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"Búsqueda semántica en articulos_normativos falló: {e}")
        return []


def insertar_o_actualizar_articulo_normativo(
    documento: str,
    articulo_numero: str,
    contenido: str,
    contenido_hash: str,
    tipo_documento: str = "ley",
    numero_norma: Optional[str] = None,
    articulo_titulo: Optional[str] = None,
    capitulo: Optional[str] = None,
    seccion: Optional[str] = None,
    embedding: Optional[List[float]] = None,
    estado: str = "vigente",
    fecha_derogacion=None,
    norma_derogatoria: Optional[str] = None,
) -> str:
    """
    Inserta (o actualiza si cambió el contenido) un artículo en
    public.articulos_normativos, identificado por (documento, articulo_numero).
    Devuelve "nuevo" | "actualizado" | "sin_cambios" | "error".
    """
    try:
        conn = get_conn()
        cur = conn.cursor()

        cur.execute(
            "SELECT contenido_hash FROM public.articulos_normativos WHERE documento = %s AND articulo_numero = %s",
            (documento, articulo_numero),
        )
        fila = cur.fetchone()
        embedding_literal = _embedding_a_literal_pgvector(embedding) if embedding else None

        if fila is None:
            cur.execute(
                """
                INSERT INTO public.articulos_normativos
                    (documento, articulo_numero, articulo_titulo, contenido, capitulo, seccion,
                     tipo_documento, numero_norma, estado, contenido_hash, embedding,
                     fecha_derogacion, norma_derogatoria)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::vector, %s, %s)
                """,
                (documento, articulo_numero, articulo_titulo, contenido, capitulo, seccion,
                 tipo_documento, numero_norma, estado, contenido_hash, embedding_literal,
                 fecha_derogacion, norma_derogatoria),
            )
            conn.commit()
            cur.close()
            return "nuevo"

        if fila[0] == contenido_hash:
            cur.close()
            return "sin_cambios"

        cur.execute(
            """
            UPDATE public.articulos_normativos
            SET articulo_titulo = %s, contenido = %s, capitulo = %s, seccion = %s,
                tipo_documento = %s, numero_norma = %s, estado = %s, contenido_hash = %s,
                embedding = COALESCE(%s::vector, embedding),
                fecha_derogacion = %s, norma_derogatoria = %s,
                actualizado_en = NOW()
            WHERE documento = %s AND articulo_numero = %s
            """,
            (articulo_titulo, contenido, capitulo, seccion, tipo_documento, numero_norma,
             estado, contenido_hash, embedding_literal, fecha_derogacion, norma_derogatoria,
             documento, articulo_numero),
        )
        conn.commit()
        cur.close()
        return "actualizado"
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"No se pudo insertar/actualizar el artículo {articulo_numero} de '{documento}': {e}")
        return "error"


def listar_documentos_normativos() -> List[Dict[str, Any]]:
    """Lista los cuerpos normativos cargados en public.articulos_normativos, con conteo de artículos."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute("""
            SELECT documento, MAX(tipo_documento), MAX(numero_norma), COUNT(*), MAX(actualizado_en)
            FROM public.articulos_normativos
            GROUP BY documento
            ORDER BY MAX(actualizado_en) DESC NULLS LAST, documento ASC
        """)
        filas = cur.fetchall()
        cur.close()
        return [
            {"documento": f[0], "tipo_documento": f[1], "numero_norma": f[2],
             "num_articulos": f[3], "ultima_actualizacion": str(f[4]) if f[4] else ""}
            for f in filas
        ]
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"No se pudo listar documentos normativos: {e}")
        return []


def buscar_articulos_constitucion_exacto(numero_articulo: str) -> Optional[Dict[str, Any]]:
    """Busca un artículo exacto por número en public.articulos_constitucion."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        for col in ("contenido", "texto_articulo"):
            try:
                cur.execute(
                    f"""
                    SELECT
                        COALESCE(articulo_numero, '') AS numero,
                        COALESCE(articulo_titulo, '') AS titulo,
                        COALESCE({col}, '')            AS texto,
                        COALESCE(capitulo, '')         AS capitulo,
                        COALESCE(seccion, '')          AS seccion
                    FROM public.articulos_constitucion
                    WHERE articulo_numero ILIKE %s OR articulo_numero = %s
                    LIMIT 1
                    """,
                    (f"%{numero_articulo}%", numero_articulo),
                )
                row = cur.fetchone()
                if row:
                    cur.close()
                    return {
                        "numero": row[0],
                        "titulo": row[1],
                        "texto": row[2],
                        "capitulo": row[3],
                        "seccion": row[4],
                    }
            except Exception:
                try:
                    conn.rollback()
                except Exception:
                    pass
                continue
        cur.close()
        return None
    except Exception as e:
        logger.warning(f"Error buscando artículo exacto {numero_articulo}: {e}")
        return None


# ════════════════════════════════════════════════════════════════════════════
# AGENTE DE CONSISTENCIA NORMATIVA (corpus vigente + búsqueda semántica pgvector)
#   El corpus contra el que se coteja es public.articulos_normativos (la misma
#   tabla que llena la pantalla "Base Legal": Código Penal, Código de Minería,
#   leyes, decretos, resoluciones...), vía buscar_articulos_normativos_semantico().
#   normativa.normas / normativa.articulos quedan como esquema legado (lo usaba
#   una carga previa vía cargar_normativa.py) y ya no se escriben ni consultan
#   en el flujo activo del Agente de Consistencia.
#   normativa.analisis_consistencia sigue siendo la bitácora de hallazgos
#   (contradicción/repetición/vacío/complementario), ahora con nombre_archivo
#   y articulo_proyecto_numero para saber a qué PDF y qué artículo del
#   proyecto corresponde cada llamada de atención.
# ════════════════════════════════════════════════════════════════════════════

def _ensure_consistencia_tables(conn) -> None:
    """Crea el esquema `normativa` (extensión pgvector + tablas) si no existe."""
    ddl = f"""
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE SCHEMA IF NOT EXISTS normativa;

    CREATE TABLE IF NOT EXISTS normativa.normas (
        id                SERIAL PRIMARY KEY,
        nombre            TEXT NOT NULL,
        tipo_norma        VARCHAR(50),
        jerarquia         INTEGER,
        fuente_archivo    TEXT,
        creado_en         TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        UNIQUE (nombre, fuente_archivo)
    );

    CREATE TABLE IF NOT EXISTS normativa.articulos (
        id                 SERIAL PRIMARY KEY,
        norma_id           INTEGER NOT NULL REFERENCES normativa.normas(id) ON DELETE CASCADE,
        numero_articulo    VARCHAR(30) NOT NULL,
        titulo_articulo    TEXT,
        texto              TEXT NOT NULL,
        parte              TEXT,
        titulo             TEXT,
        capitulo           TEXT,
        seccion            TEXT,
        vigente            BOOLEAN DEFAULT TRUE,
        embedding          vector({int(os.getenv("NVIDIA_EMBED_DIM", "2048"))}),
        creado_en          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        UNIQUE (norma_id, numero_articulo)
    );
    CREATE INDEX IF NOT EXISTS idx_normativa_articulos_vigente
        ON normativa.articulos(vigente);

    CREATE TABLE IF NOT EXISTS normativa.analisis_consistencia (
        id                          SERIAL PRIMARY KEY,
        id_proyecto                 INTEGER REFERENCES sistema.proyecto_ley(id_proyecto) ON DELETE SET NULL,
        sesion_id                   VARCHAR(36),
        task_id_mongo                VARCHAR(36),
        nombre_archivo               TEXT,
        articulo_proyecto_numero     TEXT,
        articulo_nuevo_texto         TEXT NOT NULL,
        articulo_candidato_id        BIGINT,
        articulo_candidato_documento TEXT,
        articulo_candidato_numero    TEXT,
        similitud                    NUMERIC(6,4),
        tipo_relacion                VARCHAR(20)
                                        CHECK (tipo_relacion IN
                                            ('contradiccion','repeticion','vacio_llenado',
                                             'complementario','sin_relacion')),
        justificacion                TEXT,
        sugerencia                   TEXT,
        modelo_llm                   VARCHAR(100),
        fecha_analisis                TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS idx_analisis_consistencia_proyecto
        ON normativa.analisis_consistencia(id_proyecto);
    CREATE INDEX IF NOT EXISTS idx_analisis_consistencia_sesion
        ON normativa.analisis_consistencia(sesion_id);
    CREATE INDEX IF NOT EXISTS idx_analisis_consistencia_tipo
        ON normativa.analisis_consistencia(tipo_relacion);

    ALTER TABLE normativa.analisis_consistencia
        ADD COLUMN IF NOT EXISTS nombre_archivo TEXT,
        ADD COLUMN IF NOT EXISTS articulo_proyecto_numero TEXT,
        ADD COLUMN IF NOT EXISTS articulo_candidato_documento TEXT,
        ADD COLUMN IF NOT EXISTS articulo_candidato_numero TEXT;

    CREATE INDEX IF NOT EXISTS idx_analisis_consistencia_archivo
        ON normativa.analisis_consistencia(nombre_archivo);
    """
    try:
        cur = conn.cursor()
        cur.execute(ddl)
        conn.commit()
        cur.close()
        logger.info("✅ Esquema normativa (pgvector) verificado/creado")
    except Exception as e:
        conn.rollback()
        logger.warning(
            f"⚠️  No se pudo crear el esquema normativa (¿pgvector no disponible en esta BD?): {e}"
        )
        return

    # ── Migración para bases ya existentes (creadas antes de este cambio):
    #    la tabla analisis_consistencia venía con articulo_candidato_id como
    #    FK a normativa.articulos. Los hallazgos ahora se resuelven contra
    #    public.articulos_normativos (otra tabla, otro espacio de ids), así
    #    que esa FK ya no aplica y hay que soltarla + agregar las columnas
    #    nuevas (nombre_archivo, articulo_proyecto_numero, documento/numero
    #    del candidato) si todavía no existen. Cada paso es best-effort y no
    #    interrumpe el arranque si algo falla. ──────────────────────────────
    try:
        cur = conn.cursor()
        cur.execute("""
            DO $$
            DECLARE
                fk_name TEXT;
            BEGIN
                SELECT conname INTO fk_name
                FROM pg_constraint
                WHERE conrelid = 'normativa.analisis_consistencia'::regclass
                  AND contype = 'f'
                  AND conname LIKE '%articulo_candidato_id%';
                IF fk_name IS NOT NULL THEN
                    EXECUTE format('ALTER TABLE normativa.analisis_consistencia DROP CONSTRAINT %I', fk_name);
                END IF;
            END $$;

            ALTER TABLE normativa.analisis_consistencia
                ADD COLUMN IF NOT EXISTS nombre_archivo TEXT,
                ADD COLUMN IF NOT EXISTS articulo_proyecto_numero TEXT,
                ADD COLUMN IF NOT EXISTS articulo_candidato_documento TEXT,
                ADD COLUMN IF NOT EXISTS articulo_candidato_numero TEXT;
        """)
        conn.commit()
        cur.close()
    except Exception as e:
        conn.rollback()
        logger.warning(f"⚠️  Migración de columnas nuevas en analisis_consistencia falló (no crítico): {e}")


def _embedding_a_literal_pgvector(embedding: List[float]) -> str:
    """Convierte una lista de floats al formato literal que espera pgvector: '[v1,v2,...]'."""
    return "[" + ",".join(f"{v:.8f}" for v in embedding) + "]"


def obtener_o_crear_norma_consistencia(
    nombre: str, tipo_norma: str, jerarquia: int, fuente_archivo: str
) -> Optional[int]:
    """Obtiene el id de una norma vigente ya cargada en normativa.normas, o la crea."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            "SELECT id FROM normativa.normas WHERE nombre = %s AND fuente_archivo = %s",
            (nombre, fuente_archivo),
        )
        fila = cur.fetchone()
        if fila:
            cur.close()
            return fila[0]

        cur.execute(
            """
            INSERT INTO normativa.normas (nombre, tipo_norma, jerarquia, fuente_archivo)
            VALUES (%s, %s, %s, %s)
            RETURNING id
            """,
            (nombre, tipo_norma, jerarquia, fuente_archivo),
        )
        norma_id = cur.fetchone()[0]
        conn.commit()
        cur.close()
        return norma_id
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo crear/obtener la norma '{nombre}': {e}")
        return None


def articulo_normativa_existe(norma_id: int, numero_articulo: str) -> bool:
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            "SELECT 1 FROM normativa.articulos WHERE norma_id = %s AND numero_articulo = %s",
            (norma_id, numero_articulo),
        )
        existe = cur.fetchone() is not None
        cur.close()
        return existe
    except Exception:
        return False


def insertar_articulo_normativa(
    norma_id: int,
    numero_articulo: str,
    texto: str,
    embedding: List[float],
    titulo_articulo: Optional[str] = None,
    parte: Optional[str] = None,
    titulo: Optional[str] = None,
    capitulo: Optional[str] = None,
    seccion: Optional[str] = None,
) -> Optional[int]:
    """Inserta un artículo de norma vigente junto con su embedding (pgvector)."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO normativa.articulos
                (norma_id, numero_articulo, titulo_articulo, texto, parte, titulo,
                 capitulo, seccion, embedding)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s::vector)
            RETURNING id
            """,
            (
                norma_id, numero_articulo, titulo_articulo, texto, parte, titulo,
                capitulo, seccion, _embedding_a_literal_pgvector(embedding),
            ),
        )
        articulo_id = cur.fetchone()[0]
        conn.commit()
        cur.close()
        return articulo_id
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo insertar el artículo {numero_articulo}: {e}")
        return None


def buscar_articulos_normativa_similares(
    embedding: List[float], umbral: float = 0.55, top_k: int = 8
) -> List[Dict[str, Any]]:
    """
    Busca en normativa.articulos los artículos vigentes semánticamente más
    cercanos al embedding dado (similitud coseno vía pgvector), filtrando
    por el umbral mínimo de similitud.
    """
    try:
        conn = get_conn()
        cur = conn.cursor()
        literal = _embedding_a_literal_pgvector(embedding)
        cur.execute(
            """
            SELECT a.id, a.numero_articulo, a.texto, n.nombre AS norma,
                   1 - (a.embedding <=> %s::vector) AS similitud
            FROM normativa.articulos a
            JOIN normativa.normas n ON n.id = a.norma_id
            WHERE a.vigente = TRUE AND a.embedding IS NOT NULL
            ORDER BY a.embedding <=> %s::vector
            LIMIT %s
            """,
            (literal, literal, top_k),
        )
        filas = cur.fetchall()
        cur.close()
        resultado = [
            {"id": f[0], "numero_articulo": f[1], "texto": f[2], "norma": f[3], "similitud": float(f[4])}
            for f in filas
        ]
        return [r for r in resultado if r["similitud"] >= umbral]
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  Búsqueda de consistencia normativa falló (¿corpus vacío?): {e}")
        return []


def guardar_analisis_consistencia(
    articulo_nuevo_texto: str,
    articulo_candidato_id: Optional[int],
    similitud: float,
    tipo_relacion: str,
    justificacion: str,
    sugerencia: str,
    sesion_id: Optional[str] = None,
    task_id_mongo: Optional[str] = None,
    id_proyecto: Optional[int] = None,
    modelo_llm: Optional[str] = None,
    nombre_archivo: Optional[str] = None,
    articulo_proyecto_numero: Optional[str] = None,
    articulo_candidato_documento: Optional[str] = None,
    articulo_candidato_numero: Optional[str] = None,
) -> Optional[int]:
    """
    Persiste un hallazgo (llamada de atención) del Agente de Consistencia
    Normativa. `nombre_archivo` guarda el PDF/documento enviado por el
    usuario que originó el hallazgo, y `articulo_candidato_documento` /
    `articulo_candidato_numero` identifican la norma vigente en conflicto
    tal como está en public.articulos_normativos (Código Penal, Código de
    Minería, cualquier ley cargada en "Base Legal").
    """
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO normativa.analisis_consistencia
                (id_proyecto, sesion_id, task_id_mongo, nombre_archivo,
                 articulo_proyecto_numero, articulo_nuevo_texto,
                 articulo_candidato_id, articulo_candidato_documento,
                 articulo_candidato_numero, similitud, tipo_relacion,
                 justificacion, sugerencia, modelo_llm)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                id_proyecto, sesion_id, task_id_mongo, nombre_archivo,
                articulo_proyecto_numero, articulo_nuevo_texto,
                articulo_candidato_id, articulo_candidato_documento,
                articulo_candidato_numero, round(float(similitud), 4), tipo_relacion,
                justificacion, sugerencia, modelo_llm,
            ),
        )
        id_analisis = cur.fetchone()[0]
        conn.commit()
        cur.close()
        return id_analisis
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"⚠️  No se pudo guardar el hallazgo de consistencia normativa: {e}")
        return None


def obtener_ultimos_analisis_consistencia(limit: int = 10) -> List[Dict[str, Any]]:
    """Obtiene los últimos hallazgos de consistencia normativa (para dashboard)."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """
            SELECT ac.id, ac.id_proyecto, ac.sesion_id, ac.nombre_archivo,
                   ac.articulo_proyecto_numero, ac.tipo_relacion, ac.similitud,
                   ac.justificacion, ac.sugerencia, ac.fecha_analisis,
                   ac.articulo_candidato_numero, ac.articulo_candidato_documento
            FROM normativa.analisis_consistencia ac
            ORDER BY ac.fecha_analisis DESC
            LIMIT %s
            """,
            (limit,),
        )
        filas = cur.fetchall()
        cur.close()
        return [
            {
                "id": f[0], "id_proyecto": f[1], "sesion_id": f[2], "nombre_archivo": f[3],
                "articulo_proyecto_numero": f[4], "tipo_relacion": f[5],
                "similitud": float(f[6]) if f[6] is not None else None, "justificacion": f[7],
                "sugerencia": f[8], "fecha_analisis": f[9].isoformat() if f[9] else "",
                "numero_articulo": f[10], "norma": f[11],
            }
            for f in filas
        ]
    except Exception as e:
        logger.warning(f"No se pudieron obtener los últimos análisis de consistencia: {e}")
        return []


def obtener_analisis_consistencia_por_archivo(nombre_archivo: str) -> List[Dict[str, Any]]:
    """Obtiene todas las llamadas de atención guardadas para un PDF/archivo específico."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute(
            """
            SELECT ac.id, ac.id_proyecto, ac.sesion_id, ac.articulo_proyecto_numero,
                   ac.tipo_relacion, ac.similitud, ac.justificacion, ac.sugerencia,
                   ac.fecha_analisis, ac.articulo_candidato_numero, ac.articulo_candidato_documento
            FROM normativa.analisis_consistencia ac
            WHERE ac.nombre_archivo = %s
            ORDER BY ac.fecha_analisis DESC
            """,
            (nombre_archivo,),
        )
        filas = cur.fetchall()
        cur.close()
        return [
            {
                "id": f[0], "id_proyecto": f[1], "sesion_id": f[2], "articulo_proyecto_numero": f[3],
                "tipo_relacion": f[4], "similitud": float(f[5]) if f[5] is not None else None,
                "justificacion": f[6], "sugerencia": f[7],
                "fecha_analisis": f[8].isoformat() if f[8] else "",
                "numero_articulo": f[9], "norma": f[10],
            }
            for f in filas
        ]
    except Exception as e:
        try:
            get_conn().rollback()
        except Exception:
            pass
        logger.warning(f"No se pudieron obtener los hallazgos del archivo '{nombre_archivo}': {e}")
        return []


def obtener_stats_consistencia() -> Dict[str, Any]:
    """Estadísticas rápidas del corpus normativo cargado y de los hallazgos emitidos."""
    try:
        conn = get_conn()
        cur = conn.cursor()
        cur.execute("SELECT COUNT(DISTINCT documento) FROM public.articulos_normativos")
        total_normas = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM public.articulos_normativos WHERE estado = 'vigente'")
        total_articulos = cur.fetchone()[0]
        cur.execute(
            "SELECT tipo_relacion, COUNT(*) FROM normativa.analisis_consistencia GROUP BY tipo_relacion"
        )
        por_tipo = {r[0]: r[1] for r in cur.fetchall()}
        cur.close()
        return {"total_normas": total_normas, "total_articulos": total_articulos, "hallazgos_por_tipo": por_tipo}
    except Exception as e:
        logger.warning(f"No se pudieron obtener stats de consistencia normativa: {e}")
        return {"total_normas": 0, "total_articulos": 0, "hallazgos_por_tipo": {}}

